title: "Oceanic Data"
theme: jekyll-theme-minimal
logo: "/images/oceanic.png"

nav:
  - title: "About"
    url: /about
  - title: "Quake"
    url: /quake
  - title: "Codex"
    url: /codex
  - title: "Wikipedia Analysis"
    url: /wikipedia
  - title: "Resume"
    url: /resume
